apiVersion: jupyter-on-kubernetes.test/v1alpha1
kind: JupyterNotebook
metadata:
  name: notebook
spec:
  deployment:
    image: jupyter/minimal-notebook
    serviceAccountName: default
    resources:
      requests:
        storage: 5Gi
      limits:
        memory: 512Mi
