apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-02
spec:
  title: "Jupyter on Kubernetes #2"
  description: A workshop exploring use of operators to deploy Jupyter notebooks to Kubernetes.
  workshop:
    files:
    - image:
        url: $(image_repository)/lab-jupyter-on-k8s-02-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      vcluster:
        enabled: true
        ingress:
          enabled: true
    dashboards:
    - name: Operator
      url: terminal:operator
