apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-02
spec:
  title: "Jupyter on Kubernetes #2"
  description: A workshop exploring use of operators to deploy Jupyter notebooks to Kubernetes
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-02
  content:
    files: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-02
  duration: 45m
  session:
    namespaces:
      budget: large
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: jupyter-user
      rules:
      - apiGroups:
        - jupyter-on-kubernetes.test
        resources:
        - jupyternotebooks
        verbs:
        - get
        - list
        - watch
        - create
        - patch
        - update
        - delete
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: jupyter-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: jupyter-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: session-user
      rules:
      - apiGroups:
        - ""
        resources:
        - events
        verbs:
        - create
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: session-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: session-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-crds
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: $(workshop_namespace)-crds
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
  environment:
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(workshop_namespace)-crds
      rules:
      - apiGroups:
        - apiextensions.k8s.io
        resources:
        - customresourcedefinitions
        verbs:
        - get
        - list
        - watch
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: jupyternotebooks.jupyter-on-kubernetes.test
      spec:
        scope: Namespaced
        group: jupyter-on-kubernetes.test
        names:
          plural: jupyternotebooks
          singular: jupyternotebook
          kind: JupyterNotebook
        versions:
          - name: v1alpha1
            served: true
            storage: true
        validation:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  notebook:
                    type: object
                    properties:
                      interface:
                        type: string
                  deployment:
                    type: object
                    properties:
                      image:
                        type: string
                      serviceAccountName:
                        type: string
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              memory:
                                type: string
                              storage:
                                type: string
                          limits:
                            type: object
                            properties:
                              memory:
                                type: string
                              storage:
                                type: string
                  storage:
                    type: object
                    properties:
                      claimName:
                        type: string
                      subPath:
                        type: string
              status:
                type: object
        additionalPrinterColumns:
        - name: URL
          type: string
          priority: 0
          description: URL for acessing the Jupyter notebook.
          JSONPath: .status.jupyter.notebook.url
        - name: Password
          type: string
          priority: 0
          description: Password for accessing the Jupyter notebook.
          JSONPath: .status.jupyter.notebook.password
