apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyternotebooks.jupyter-on-kubernetes.test
spec:
  scope: Namespaced
  group: jupyter-on-kubernetes.test
  names:
    plural: jupyternotebooks
    singular: jupyternotebook
    kind: JupyterNotebook
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: object
                  properties:
                    image:
                      type: string
                    serviceAccountName:
                      type: string
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            memory:
                              type: string
                            storage:
                              type: string
                        limits:
                          type: object
                          properties:
                            memory:
                              type: string
                            storage:
                              type: string
                storage:
                  type: object
                  properties:
                    claimName:
                      type: string
                    subPath:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
      - name: URL
        type: string
        priority: 0
        description: URL for acessing the Jupyter notebook.
        jsonPath: .status.jupyter.notebook.url
      - name: Password
        type: string
        priority: 0
        description: Password for accessing the Jupyter notebook.
        jsonPath: .status.jupyter.notebook.password
