apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook
  labels:
    app: notebook
data:
  jupyter_server_config.json: |-
    {
      "IdentityProvider": {
        "hashed_password": "argon2:$argon2id$v=19$m=10240,t=10,p=8$nASioQSh/HSW9xH+e4cJxQ$MIDOSN4q1E8kcXohx6DlnllST0tFa223YVnm8bfpn6o"
      }
    }
