apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook
  labels:
    app: notebook
data:
  jupyter_server_config.json: |-
    {
      "ServerApp": {
        "password": "argon2:$argon2id$v=19$m=10240,t=10,p=8$OCz4NRN9RNJQqPKQCx5OyQ$YogG0k+sxOe8LohqEzAQuUS/voP1xQY5aTH2oNG/LGs"
      }
    }
